module.exports = {
  SHOP_FOR_CREATE: 'SHOP_FOR_CREATE',
  SHOP_FOR_COMPLETE: 'SHOP_FOR_COMPLETE',
  SHOP_FOR_DESTROY: 'SHOP_FOR_DESTROY',
  SHOP_FOR_DESTROY_COMPLETED: 'SHOP_FOR_DESTROY_COMPLETED',
  SHOP_FOR_UNDO_COMPLETE: 'SHOP_FOR_UNDO_COMPLETE',
  SHOP_FOR_UPDATE_TEXT: 'SHOP_FOR_UPDATE_TEXT',
  RECIPE_FINDER_ITEM_DROP:'RECIPE_FINDER_ITEM_DROP',
  SCHEDULE_MEAL:'SCHEDULE_MEAL',
  UNSET_ALL_ITEMS_IN_RECIPE_FINDER:'UNSET_ALL_ITEMS_IN_RECIPE_FINDER',
  FIND_RECIPE:"FIND_RECIPE"
};